version: '2.1'
services:
  mc:
    image: itzg/minecraft-server
    container_name: mine:25565
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MODE: survival
      SERVER_NAME: Morty
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /media/docker/minecraft/:/data