version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - FILE__MYSQL_ROOT_PASSWORD=/tmp/secrets/root_password
      - TZ=Europe/London
    volumes:
      - /opt/appdata/mariadb:/config
      - ./run/secrets/mariadb:/tmp/secrets
    ports:
      - 3306:3306
    restart: unless-stopped
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - mariadb
    volumes:
      - /opt/appdata/nextcloud:/var/www/html/config
      - /media/docker/nextcloud:/var/www/html/data
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
    secrets:
      - mysql_password
secrets:
  nextcloud_admin_password:
    file: ./run/secrets/nextcloud/mysql_password