version: '2.1'
services:
  mc:
    image: itzg/minecraft-bedrock-server
    container_name: mine
    ports:
      - 12312:19132/udp
    environment:
      EULA: "TRUE"
      MODE: survival
      DIFFICULTY: normal
      SERVER_NAME: Morty
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - mine:/data

volumes:
  mine: {}
