version: '3'
services:
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "8082:8082"
      - "5000-5150:5000-5150"
    volumes:
      - /opt/appdata/traccar/logs:/opt/traccar/logs
      - /media/traccar/data:/opt/traccar/data

