version: '3.4'
services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: mine-1
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: "hib's mine - 1 "
    ports:
      - 19132:19132/udp
    volumes:
      - /media/docker/minecraft/mine-1:/data
    stdin_open: true
    tty: true