version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=/tmp/secrets/root_password
      - TZ=Europe/London
      # - MYSQL_DATABASE=USER_DB_NAME #optional
      # - MYSQL_USER=MYSQL_USER #optional
      # - MYSQL_PASSWORD=DATABASE_PASSWORD #optionaloptional
    volumes:
      - /media/docker/mariadb:/config
      - ./run/secrets/mariadb:/tmp/secrets
    ports:
      - 3306:3306
    restart: unless-stopped