version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /opt/appdata/qbittorrent/config:/config
      - /media/downloads:/media/downloads
      - /media/cinema:/media/cinema
      - /media/tv:/media/tv
    ports:
      - 8088:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped


# services:
#   deluge:
#     image: lscr.io/linuxserver/deluge:latest
#     container_name: deluge
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Europe/London
#       - DELUGE_LOGLEVEL=error #optional
#     volumes:
#       - /opt/appdata/deluge/config:/config
#       - /media:/media
#     ports:
#       - 8112:8112
#       - 6881:6881
#       - 6881:6881/udp
#     restart: unless-stopped

#version: "2.1"
#services:
  # deluge:
  #   image: linuxserver/deluge:latest
  #   restart: unless-stopped
  #   environment:
  #     - PUID=113
  #     - PGID=1001
  #     - UMASK_SET=002
  #     - TZ=Europe/London
  #   volumes:
  #     - ./x/deluge/config:/config
  #     - ./x/deluge/trigger-decompress.sh:/usr/local/bin/trigger-decompress.sh:ro
  #     - ./x/deluge/downloads:/downloads
  #     - ./x/media/raid/videos:/videos
  # flexget:
  #  image: cpoppema/docker-flexget:latest
  #  restart: unless-stopped
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Europe/London
  #    - TORRENT_PLUGIN=deluge
  #    - FLEXGET_LOG_LEVEL=info
  #  ports:
  #    - 5055:5050
  #  volumes:
  #  - ./x/flexget:/config
  #    - ./x/flexget/99-install-other-deps:/etc/cont-init.d/99-install-other-deps:ro
  #    - ./x/dbox/dropbox/Flexget/db-config.sqlite:/config/db-config.sqlite
  #    - ./x/dbox/dropbox/Flexget/secretfile.yml:/config/secretfile.yml:ro
  #    - ./x/deluge/downloads:/downloads:ro
  #    - ./x/media/raid/videos:/videos
  # flexget:
  #   image: wiserain/flexget
  #   container_name: flexget
  #   restart: always
  #   environment:
  #     - PUID=998
  #     - PGID=998
  #     - TZ=Europe/London
  #     - FG_WEBUI_PASSWD=qweQWE123!@#
  #     - FG_LOG_LEVEL=info
  #   ports:
  #     - 5050:5050
  #   volumes:
  #     - ./ss/flexget:/config
  #     - ./ss/tank/Video:/tank/Video
