version: '2.1'
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "mcj3:/data"
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      JVM_DD_OPTS: " disable.watchdog:true"
      # More aggressive settings for demo purposes
      AUTOPAUSE_TIMEOUT_INIT: "30"
      AUTOPAUSE_TIMEOUT_EST: "10"
    restart: unless-stopped

volumes:
  mcj3: {}
