version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - VIRTUAL_HOST=sonarr.bartczak.eu
      - HTTPS_METHOD=redirect
      - LETSENCRYPT_HOST=sonarr.bartczak.eu
      - LETSENCRYPT_EMAIL=admin@sonarr.bartczak.eu
    volumes:
      - /home/docker/storage/sonarr/config:/config
      - /data/media/tvSeries:/data/media/tvSeries
      - /data/media/tvSeries-anim:/data/media/tvSeries-anim
      - /data/transmission-incomplete:/downloads
    ports:
      - 8089:8989
    restart: unless-stopped

